# Generated by Django 4.1.5 on 2023-01-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='precent',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='salary',
            field=models.IntegerField(default=37500),
        ),
    ]
