# Generated by Django 4.1.5 on 2023-01-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_qualification_precent_alter_qualification_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='precent',
            field=models.IntegerField(default=12, verbose_name='Процент от продаж'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='salary',
            field=models.IntegerField(default=37500, verbose_name='Оклад'),
        ),
    ]
